#include <jni.h>
#include <string>
#include <cstdlib>
#include "libargotunnel_core.h" // Header generated by Go buildmode=c-shared

extern "C" JNIEXPORT jstring JNICALL
Java_com_argotunnel_SlipTunnelApp_startGoEngine(JNIEnv* env, jobject /* this */, jstring dbPath, jstring key) {
    const char* path_cstr = env->GetStringUTFChars(dbPath, nullptr);
    const char* key_cstr = env->GetStringUTFChars(key, nullptr);

    // Call Phase 1 Go Exported Function
    char* result = StartEngine(const_cast<char*>(path_cstr), const_cast<char*>(key_cstr));

    env->ReleaseStringUTFChars(dbPath, path_cstr);
    env->ReleaseStringUTFChars(key, key_cstr);

    jstring ret = env->NewStringUTF(result);
    free(result); // Free memory allocated by Go's C.CString

    return ret;
}

extern "C" JNIEXPORT jstring JNICALL
Java_com_argotunnel_SlipTunnelApp_stopGoEngine(JNIEnv* env, jobject /* this */) {
    char* result = StopEngine();
    jstring ret = env->NewStringUTF(result);
    free(result);
    return ret;
}
